name: Style, unit, functional tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run_style_check:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: hw7
          environment-file: environment.yml
      - run: pycodestyle $(git ls-files "*.py")
  run_unit_tests:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: hw7
          environment-file: environment.yml
      - run: |
             cd tests
             python -m unittest test_data_processor
  run_functional_tests:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: hw7
          environment-file: environment.yml
      - run: |
             cd tests
             bash test_plotter.sh
